[package]
name = "advent"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "advent"
path = "src/lib.rs"

[[bin]]
name = "advent"
path = "src/cli.rs"
required-features = ["fetch", "cli"]

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking"], optional = true}
url = { version = "2.2.2", optional = true}
dirs = "3.0"
# scraper = "0.12.0"
anyhow = "1.0.43"
clap = { version = "2.33.3", optional = true}


[features]
fetch = ["reqwest", "url"]
cli = ["clap"]
